//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Editorial
{
    public Editorial()
    {
        this.Libros = new HashSet<Libro>();
    }

    public short IDEditorial { get; set; }
    public string Nombre { get; set; }
    public string Direccion { get; set; }
    public string Telefono { get; set; }
    public string Web { get; set; }
    public string E_mail { get; set; }

    public virtual ICollection<Libro> Libros { get; set; }
}
