//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GetAllDataSP
{
    public short IDLibro { get; set; }
    public string ISBN { get; set; }
    public string Título { get; set; }
    public string Autor { get; set; }
    public short Páginas { get; set; }
    public decimal Precio { get; set; }
    public Nullable<short> Stock { get; set; }
    public System.DateTime Publicación { get; set; }
    public string Descripción { get; set; }
    public string Editorial { get; set; }
    public string Dirección { get; set; }
    public string Teléfono { get; set; }
    public string Web { get; set; }
    public string Correo { get; set; }
}
