//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Libro
{
    public short IDLibro { get; set; }
    public string ISBN { get; set; }
    public string Titulo { get; set; }
    public string Autor { get; set; }
    public short IDEditorial { get; set; }
    public short Paginas { get; set; }
    public decimal Precio { get; set; }
    public byte[] Imagen { get; set; }
    public System.DateTime Publicacion { get; set; }
    public string Descripcion { get; set; }
    public Nullable<short> Stock { get; set; }

    public virtual Editorial Editorial { get; set; }
}
